# Database
DATABASES:
  default:
    ENGINE: django.db.backends.sqlite3
    NAME: db_from_config.sqlite3

# Debug
DEBUG: true

# Allowed hosts
ALLOWED_HOSTS:
  - localhost
  - 127.0.0.1

# CORS
CORS_ALLOWED_ORIGINS:
  - http://localhost:4200
  - http://127.0.0.1:4200
